# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 if Vagrant.has_plugin? "vagrant-vbguest"
	config.vbguest.no_install = true
	config.vbguest.auto_update = false
	config.vbguest.no_remote = true
end

config.vm.define :firewall do |firewall|
	firewall.vm.box = "bento/centos-7"
	firewall.vm.network :private_network, ip: "192.168.100.3"
	firewall.vm.network "public_network", use_dhcp_assigned_default_route: true
	firewall.vm.hostname = "firewall"
end

config.vm.define :servidor do |servidor|
	servidor.vm.box = "bento/centos-7"
	servidor.vm.network :private_network, ip: "192.168.100.5"
	servidor.vm.network :forwarded_port, guest: 80, host:5567
	servidor.vm.hostname = "servidor"
end

config.vm.define :dnstest do |dnstest|
	dnstest.vm.box = "bento/ubuntu-20.04"
	dnstest.vm.network :private_network, ip: "192.168.20.2"
	dnstest.vm.hostname = "dnstest"
	dnstest.vm.provision "shell", path: "script.sh"
end
end